services:
    bot:
        container_name: mediaEblan-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - DOWNLOAD_DIR=/usr/src/app/tmp
        env_file:
            - path: ./.env
              required: false
        tmpfs:
            - /usr/src/app/tmp:size=2g
