services:
    postgres:
            container_name: mediaEblan-postgres
            image: postgres:latest
            restart: unless-stopped
            environment:
                - POSTGRES_USER=mediaEblan
                - POSTGRES_PASSWORD=a1f0d5c54ee88a67e10ea3f1
                - POSTGRES_DB=mediaEblan
            ports:
                - 5432:5432
            volumes:
                - postgres_data:/var/lib/postgresql
volumes:
    postgres_data:
    
networks:
    default: {}